# Generated by Django 6.0 on 2026-01-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltaxon',
            name='classification_path',
            field=models.JSONField(default=list, help_text='Clasificación ORDENADA root->leaf tal como viene de CoL (lista de {rank,name}).'),
        ),
    ]
