# Generated by Django 5.2.9 on 2026-02-09 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_samplingrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCBIGenome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(db_index=True, help_text='Accession del ensamblaje (ej: GCF_000001405.40)', max_length=64, unique=True)),
                ('organism_name', models.CharField(blank=True, default='', max_length=255)),
                ('refseq_category', models.CharField(blank=True, db_index=True, default='', help_text='reference genome / representative genome / na', max_length=64)),
                ('genome_level', models.CharField(blank=True, db_index=True, default='', help_text='Complete Genome / Chromosome / Scaffold / Contig', max_length=64)),
                ('genome_coverage', models.FloatField(blank=True, help_text='Cobertura del genoma', null=True)),
                ('contig_n50_kb', models.FloatField(blank=True, help_text='Contig N50 en kilobases', null=True)),
                ('scaffold_n50_kb', models.FloatField(blank=True, help_text='Scaffold N50 en kilobases', null=True)),
                ('scaffold_count', models.PositiveIntegerField(blank=True, help_text='Número de scaffolds', null=True)),
                ('quality_score', models.FloatField(db_index=True, default=0.0, help_text='Score de calidad calculado')),
                ('has_proteome', models.BooleanField(db_index=True, default=False, help_text='Indica si tiene proteoma válido (.faa)')),
                ('proteome_quality', models.CharField(blank=True, default='', help_text='Calidad del proteoma: good / poor / unknown', max_length=32)),
                ('is_selected', models.BooleanField(db_index=True, default=False, help_text='Marcado como seleccionado para investigación')),
                ('is_best_for_taxon', models.BooleanField(db_index=True, default=False, help_text='Es el mejor ensamblaje para este taxón')),
                ('raw', models.JSONField(default=dict, help_text='Payload original de la API NCBI')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de obtención de datos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxon', models.ForeignKey(help_text='Taxón NCBI asociado', on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='taxonomy.taxon')),
            ],
            options={
                'verbose_name': 'NCBI Genome',
                'verbose_name_plural': 'NCBI Genomes',
                'ordering': ['-quality_score', '-is_best_for_taxon'],
                'indexes': [models.Index(fields=['taxon', 'is_best_for_taxon'], name='taxonomy_nc_taxon_i_acb25b_idx'), models.Index(fields=['refseq_category'], name='taxonomy_nc_refseq__c82d89_idx'), models.Index(fields=['genome_level'], name='taxonomy_nc_genome__7fb97b_idx'), models.Index(fields=['quality_score'], name='taxonomy_nc_quality_a4e3d4_idx'), models.Index(fields=['has_proteome'], name='taxonomy_nc_has_pro_9e919b_idx')],
            },
        ),
    ]
