# Generated by Django 5.2.9 on 2026-02-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_add_ncbi_genome'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCBISyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=16)),
                ('trigger', models.CharField(choices=[('scheduled', 'Programado'), ('manual', 'Manual'), ('webhook', 'Webhook')], default='manual', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', help_text='ID de la tarea Celery', max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Configuración usada para esta sincronización')),
                ('total_taxa', models.PositiveIntegerField(default=0)),
                ('processed_taxa', models.PositiveIntegerField(default=0)),
                ('successful_taxa', models.PositiveIntegerField(default=0)),
                ('failed_taxa', models.PositiveIntegerField(default=0)),
                ('skipped_taxa', models.PositiveIntegerField(default=0)),
                ('genomes_created', models.PositiveIntegerField(default=0)),
                ('genomes_updated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log', models.JSONField(default=list, help_text='Log detallado de la ejecución')),
            ],
            options={
                'verbose_name': 'NCBI Sync Run',
                'verbose_name_plural': 'NCBI Sync Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='taxonomy_nc_status_ff0ea7_idx'), models.Index(fields=['created_at'], name='taxonomy_nc_created_7e55a1_idx'), models.Index(fields=['celery_task_id'], name='taxonomy_nc_celery__d5c698_idx')],
            },
        ),
    ]
