# Generated by Django 5.2.9 on 2026-02-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_extend_ncbigenome_for_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('fetching_ncbi', 'Descargando NCBI'), ('matching_col', 'Sincronizando COL'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=24)),
                ('kingdom', models.CharField(choices=[('metazoa', 'Metazoa'), ('fungi', 'Fungi'), ('viridiplantae', 'Viridiplantae'), ('bacteria', 'Bacteria'), ('archaea', 'Archaea')], db_index=True, default='metazoa', max_length=32)),
                ('config', models.JSONField(default=dict, help_text='Configuración de la sincronización (límite, filtros, etc.)')),
                ('ncbi_total', models.PositiveIntegerField(default=0)),
                ('ncbi_fetched', models.PositiveIntegerField(default=0)),
                ('ncbi_filtered', models.PositiveIntegerField(default=0)),
                ('taxa_created', models.PositiveIntegerField(default=0)),
                ('genomes_created', models.PositiveIntegerField(default=0)),
                ('col_total', models.PositiveIntegerField(default=0)),
                ('col_matched', models.PositiveIntegerField(default=0)),
                ('col_unmatched', models.PositiveIntegerField(default=0)),
                ('external_taxa_created', models.PositiveIntegerField(default=0)),
                ('crosswalks_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log', models.JSONField(default=list, help_text='Log detallado de la ejecución')),
            ],
            options={
                'verbose_name': 'Taxon Sync Run',
                'verbose_name_plural': 'Taxon Sync Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='taxonomy_ta_status_397dc0_idx'), models.Index(fields=['kingdom'], name='taxonomy_ta_kingdom_8658bc_idx'), models.Index(fields=['created_at'], name='taxonomy_ta_created_7859c9_idx')],
            },
        ),
    ]
