# Generated by Django 5.2.9 on 2026-02-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0011_remove_taxon_last_col_checked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=16)),
                ('kingdoms_searched', models.JSONField(default=list, help_text='List of kingdoms searched in this run')),
                ('total_scanned', models.PositiveIntegerField(default=0)),
                ('new_species_found', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Discovery Run',
                'verbose_name_plural': 'Discovery Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.PositiveIntegerField(help_text='NCBI Taxonomy ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, default='', max_length=255)),
                ('kingdom', models.CharField(blank=True, default='', max_length=64)),
                ('accession', models.CharField(help_text='Best genome accession', max_length=64)),
                ('quality_score', models.FloatField(default=0.0)),
                ('genome_level', models.CharField(blank=True, default='', max_length=64)),
                ('refseq_category', models.CharField(blank=True, default='', max_length=64)),
                ('protein_coding', models.PositiveIntegerField(blank=True, null=True)),
                ('scaffold_n50_kb', models.FloatField(blank=True, null=True)),
                ('genome_coverage', models.FloatField(blank=True, null=True)),
                ('total_sequence_length', models.BigIntegerField(blank=True, null=True)),
                ('is_imported', models.BooleanField(db_index=True, default=False, help_text='Whether this species has been imported into the database')),
                ('is_dismissed', models.BooleanField(db_index=True, default=False, help_text='Marked as not interesting by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='taxonomy.discoveryrun')),
            ],
            options={
                'verbose_name': 'Discovered Species',
                'verbose_name_plural': 'Discovered Species',
                'ordering': ['-quality_score'],
                'indexes': [models.Index(fields=['taxid'], name='taxonomy_di_taxid_4d5fa6_idx'), models.Index(fields=['quality_score'], name='taxonomy_di_quality_d7b376_idx'), models.Index(fields=['is_imported'], name='taxonomy_di_is_impo_4720a1_idx')],
                'unique_together': {('discovery_run', 'taxid')},
            },
        ),
    ]
