# Generated by Django 5.2.9 on 2026-02-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_add_discovery_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncbigenome',
            name='assembly_method',
            field=models.TextField(blank=True, default='', help_text='Assembly method'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='common_name',
            field=models.TextField(blank=True, default='', help_text='Organism common name'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='directory_name',
            field=models.TextField(blank=True, default='', help_text='NCBI directory name'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='organism_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='sequencing_tech',
            field=models.TextField(blank=True, default='', help_text='Sequencing technology'),
        ),
    ]
