# Generated by Django 5.2.9 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0013_expand_genome_text_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Optional name for this configuration', max_length=128)),
                ('max_sample_size', models.PositiveIntegerField(help_text='Maximum number of species to select')),
                ('start_rank', models.CharField(choices=[('kingdom', 'Kingdom'), ('phylum', 'Phylum'), ('class', 'Class'), ('order', 'Order'), ('family', 'Family'), ('genus', 'Genus'), ('species', 'Species')], default='phylum', help_text='Start rank for taxonomic grouping (how species are grouped)', max_length=32)),
                ('end_rank', models.CharField(choices=[('kingdom', 'Kingdom'), ('phylum', 'Phylum'), ('class', 'Class'), ('order', 'Order'), ('family', 'Family'), ('genus', 'Genus'), ('species', 'Species')], default='species', help_text='End rank — distribution resolves down to this level before selecting species', max_length=32)),
                ('strategy', models.CharField(choices=[('none', 'None (natural order)'), ('random', 'Random'), ('proportional', 'Proportional'), ('balanced', 'Balanced')], default='proportional', help_text='Sampling strategy', max_length=32)),
                ('scope_kingdom', models.CharField(blank=True, default='', help_text='Restrict to a specific kingdom (e.g. Animalia)', max_length=64)),
                ('scope_phylum', models.CharField(blank=True, default='', help_text='Restrict to a specific phylum (e.g. Chordata)', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('executed', 'Executed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Sampling result payload')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
