# Generated by Django 6.0 on 2026-01-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('input_type', models.CharField(choices=[('taxid', 'NCBI taxid'), ('name', 'Scientific name')], max_length=16)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('parameters', models.JSONField(default=dict)),
                ('input_payload', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalTaxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(db_index=True, default='col', help_text="Fuente externa (ej. 'col')", max_length=32)),
                ('dataset_code', models.CharField(db_index=True, help_text='Dataset real (ej. COL25.12, 3LR, ...)', max_length=32)),
                ('external_id', models.CharField(db_index=True, help_text='ID externo en la fuente', max_length=128)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('rank', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, help_text='accepted / synonym / misapplied / unknown', max_length=64)),
                ('accepted_external_id', models.CharField(blank=True, db_index=True, default='', help_text='external_id aceptado (si este registro es sinónimo)', max_length=128)),
                ('parent_external_id', models.CharField(blank=True, db_index=True, default='', help_text='external_id del parent (para reconstruir árbol)', max_length=128)),
                ('classification', models.JSONField(default=dict, help_text='Clasificación jerárquica completa (rank -> name) desde CoL')),
                ('raw', models.JSONField(default=dict, help_text='Payload original (auditoría)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.ForeignKey(blank=True, help_text='FK interna al taxón aceptado (si aplica y está importado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonyms', to='taxonomy.externaltaxon')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent taxon (FK interno) si ya fue importado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.externaltaxon')),
            ],
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'INFO'), ('warn', 'WARN'), ('error', 'ERROR')], db_index=True, max_length=8)),
                ('event', models.CharField(choices=[('ncbi_query', 'NCBI_QUERY'), ('col_query', 'COL_QUERY'), ('mapping', 'MAPPING'), ('tree_build', 'TREE_BUILD'), ('selection', 'SELECTION'), ('io', 'IO'), ('other', 'OTHER')], db_index=True, max_length=32)),
                ('message', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='taxonomy.resolutionrun')),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('taxid', models.PositiveIntegerField(help_text='NCBI Taxonomy ID', primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(db_index=True, max_length=255)),
                ('rank', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scientific_name'], name='taxonomy_ta_scienti_8337d7_idx'), models.Index(fields=['rank'], name='taxonomy_ta_rank_6fd83d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxonCrosswalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('decision', models.CharField(choices=[('high', 'High confidence'), ('needs_review', 'Needs review'), ('no_match', 'No match')], db_index=True, max_length=32)),
                ('method', models.CharField(choices=[('exact', 'Exact name match'), ('exact_rank', 'Exact name + rank'), ('trigram', 'Trigram similarity'), ('lineage', 'Lineage constrained'), ('manual', 'Manual curation')], db_index=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('curation_level', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('reviewed', 'Reviewed')], db_index=True, default='auto', max_length=16)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosswalks', to='taxonomy.externaltaxon')),
                ('ncbi_taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosswalks', to='taxonomy.taxon')),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('process_status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='queued', max_length=16)),
                ('decision', models.CharField(blank=True, choices=[('high', 'High confidence'), ('needs_review', 'Needs review'), ('no_match', 'No match')], db_index=True, max_length=32, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='taxonomy.resolutionrun')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.taxon')),
                ('crosswalk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_items', to='taxonomy.taxoncrosswalk')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonNameIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ncbi', 'NCBI'), ('col', 'Catalogue of Life')], db_index=True, max_length=8)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('name_raw', models.CharField(max_length=255)),
                ('name_canonical', models.CharField(db_index=True, max_length=255)),
                ('rank', models.CharField(db_index=True, max_length=64)),
                ('parent_source_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('is_accepted', models.BooleanField(default=True)),
                ('lineage', models.JSONField(default=dict)),
                ('normalization_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'rank'], name='taxonomy_ta_source_bd58ae_idx'), models.Index(fields=['source', 'name_canonical'], name='taxonomy_ta_source_d35a9f_idx'), models.Index(fields=['source', 'parent_source_id'], name='taxonomy_ta_source_ebb67e_idx'), models.Index(fields=['source', 'normalization_version'], name='taxonomy_ta_source_d953fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='externaltaxon',
            index=models.Index(fields=['system', 'dataset_code'], name='taxonomy_ex_system_21871c_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltaxon',
            index=models.Index(fields=['name'], name='taxonomy_ex_name_f41d27_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltaxon',
            index=models.Index(fields=['rank'], name='taxonomy_ex_rank_e89416_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltaxon',
            index=models.Index(fields=['status'], name='taxonomy_ex_status_62fc3a_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltaxon',
            index=models.Index(fields=['parent_external_id'], name='taxonomy_ex_parent__87b867_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltaxon',
            index=models.Index(fields=['accepted_external_id'], name='taxonomy_ex_accepte_530cfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaltaxon',
            constraint=models.UniqueConstraint(fields=('system', 'dataset_code', 'external_id'), name='uq_external_taxon_source'),
        ),
        migrations.AddIndex(
            model_name='runevent',
            index=models.Index(fields=['level'], name='taxonomy_ru_level_bf10c2_idx'),
        ),
        migrations.AddIndex(
            model_name='runevent',
            index=models.Index(fields=['event'], name='taxonomy_ru_event_6fdd66_idx'),
        ),
        migrations.AddIndex(
            model_name='runevent',
            index=models.Index(fields=['created_at'], name='taxonomy_ru_created_aec0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='taxoncrosswalk',
            index=models.Index(fields=['decision'], name='taxonomy_ta_decisio_55f7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='taxoncrosswalk',
            index=models.Index(fields=['score'], name='taxonomy_ta_score_881a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='taxoncrosswalk',
            index=models.Index(fields=['method'], name='taxonomy_ta_method_94a63e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxoncrosswalk',
            index=models.Index(fields=['is_active'], name='taxonomy_ta_is_acti_0df878_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxoncrosswalk',
            constraint=models.UniqueConstraint(fields=('ncbi_taxon', 'external_taxon'), name='uq_ncbi_col_pair'),
        ),
        migrations.AddConstraint(
            model_name='taxoncrosswalk',
            constraint=models.UniqueConstraint(condition=models.Q(('decision', 'high'), ('is_active', True)), fields=('ncbi_taxon',), name='uq_active_high_crosswalk_per_ncbi_taxon'),
        ),
        migrations.AddIndex(
            model_name='resolutionitem',
            index=models.Index(fields=['process_status'], name='taxonomy_re_process_7d869c_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionitem',
            index=models.Index(fields=['decision'], name='taxonomy_re_decisio_2c7970_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionitem',
            index=models.Index(fields=['score'], name='taxonomy_re_score_c7df09_idx'),
        ),
    ]
