# Generated by Django 6.0 on 2026-02-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_externaltaxon_classification_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope_root_key', models.TextField(blank=True, default='')),
                ('params', models.JSONField(default=dict)),
                ('sampling_payload', models.JSONField(default=dict)),
                ('tree_newick', models.TextField(blank=True, default='')),
                ('tree_json', models.JSONField(default=dict)),
            ],
        ),
    ]
