# Generated by Django 5.2.9 on 2026-02-10 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_add_ncbi_sync_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbigenome',
            name='class_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='col_match_notes',
            field=models.TextField(blank=True, default='', help_text='Notas sobre el matching con CoL'),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='col_match_status',
            field=models.CharField(choices=[('unmatched', 'Sin vincular'), ('matched', 'Vinculado'), ('needs_review', 'Requiere revisión'), ('no_match', 'Sin coincidencia en CoL')], db_index=True, default='unmatched', help_text='Estado de vinculación con CoL', max_length=32),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='Nombre común del organismo', max_length=255),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='directory_name',
            field=models.CharField(blank=True, default='', help_text='Nombre de directorio en NCBI', max_length=255),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='external_taxon',
            field=models.ForeignKey(blank=True, help_text='Taxón CoL vinculado (via matching)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncbi_genomes', to='taxonomy.externaltaxon'),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='genes',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de genes', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='phylum',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='protein_coding',
            field=models.PositiveIntegerField(blank=True, help_text='Número de genes codificantes de proteínas', null=True),
        ),
        migrations.AddIndex(
            model_name='ncbigenome',
            index=models.Index(fields=['phylum'], name='taxonomy_nc_phylum_fc504a_idx'),
        ),
        migrations.AddIndex(
            model_name='ncbigenome',
            index=models.Index(fields=['class_name'], name='taxonomy_nc_class_n_3e0645_idx'),
        ),
        migrations.AddIndex(
            model_name='ncbigenome',
            index=models.Index(fields=['col_match_status'], name='taxonomy_nc_col_mat_1fbdee_idx'),
        ),
    ]
