# Generated by Django 5.2.9 on 2026-02-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_add_taxon_sync_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonsyncrun',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID de la tarea Celery', max_length=255),
        ),
    ]
