# Generated by Django 5.2.9 on 2026-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_add_celery_task_id_to_taxonsyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbigenome',
            name='annotation_provider',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Proveedor de anotación (NCBI RefSeq, WormBase, etc.)', max_length=128),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='annotation_status',
            field=models.CharField(blank=True, default='', help_text='Estado de anotación (Full annotation, etc.)', max_length=64),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='assembly_method',
            field=models.CharField(blank=True, default='', help_text='Método de ensamblaje', max_length=255),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='busco_complete',
            field=models.FloatField(blank=True, help_text='BUSCO: % genes completos', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='busco_duplicated',
            field=models.FloatField(blank=True, help_text='BUSCO: % duplicados', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='busco_fragmented',
            field=models.FloatField(blank=True, help_text='BUSCO: % fragmentados', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='busco_lineage',
            field=models.CharField(blank=True, default='', help_text='Linaje BUSCO usado (ej: actinopterygii_odb10)', max_length=64),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='busco_missing',
            field=models.FloatField(blank=True, help_text='BUSCO: % faltantes', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='busco_single_copy',
            field=models.FloatField(blank=True, help_text='BUSCO: % single copy', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='chromosome_count',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de cromosomas', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='contig_count',
            field=models.PositiveIntegerField(blank=True, help_text='Número de contigs', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='ecotype',
            field=models.CharField(blank=True, default='', help_text='Ecotipo del organismo', max_length=128),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='gc_percent',
            field=models.FloatField(blank=True, help_text='Porcentaje de GC del genoma', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='non_coding_genes',
            field=models.PositiveIntegerField(blank=True, help_text='Número de genes no codificantes', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='pseudogenes',
            field=models.PositiveIntegerField(blank=True, help_text='Número de pseudogenes', null=True),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='release_date',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Fecha de liberación del ensamblaje', max_length=20),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='sequencing_tech',
            field=models.CharField(blank=True, default='', help_text='Tecnología de secuenciación', max_length=255),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='source_database',
            field=models.CharField(blank=True, db_index=True, default='', help_text='refseq o genbank', max_length=16),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='strain',
            field=models.CharField(blank=True, default='', help_text='Cepa/strain del organismo', max_length=128),
        ),
        migrations.AddField(
            model_name='ncbigenome',
            name='total_sequence_length',
            field=models.BigIntegerField(blank=True, help_text='Tamaño total del genoma en bp', null=True),
        ),
    ]
