# Generated by Django on 2026-02-11
# Adds last_col_checked_at field to Taxon model

from django.db import migrations, models
from django.utils import timezone


def mark_existing_crosswalks_as_checked(apps, schema_editor):
    """
    Mark all taxons that already have an active crosswalk as checked.
    This ensures they won't be re-checked unnecessarily.
    """
    Taxon = apps.get_model('taxonomy', 'Taxon')
    TaxonCrosswalk = apps.get_model('taxonomy', 'TaxonCrosswalk')
    
    # Get taxids with active crosswalks
    taxids_with_crosswalk = TaxonCrosswalk.objects.filter(
        is_active=True
    ).values_list('ncbi_taxon_id', flat=True).distinct()
    
    # Update those taxons
    Taxon.objects.filter(
        taxid__in=taxids_with_crosswalk,
        last_col_checked_at__isnull=True
    ).update(last_col_checked_at=timezone.now())


def reverse_mark(apps, schema_editor):
    """Reverse: set all last_col_checked_at to NULL"""
    Taxon = apps.get_model('taxonomy', 'Taxon')
    Taxon.objects.update(last_col_checked_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0009_add_extended_genome_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="last_col_checked_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Last time this taxon was checked against COL (match or no match)",
                null=True,
            ),
        ),
        migrations.RunPython(mark_existing_crosswalks_as_checked, reverse_mark),
    ]
