# Generated by Django 5.2.9 on 2026-02-12 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0010_add_last_col_checked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='last_col_checked_at',
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='accepted',
            field=models.ForeignKey(blank=True, help_text='Internal FK to the accepted taxon (if applicable and already imported)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonyms', to='taxonomy.externaltaxon'),
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='accepted_external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Accepted external_id (if this record is a synonym)', max_length=128),
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='classification',
            field=models.JSONField(default=dict, help_text='Full hierarchical classification (rank -> name) from CoL'),
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='classification_path',
            field=models.JSONField(default=list, help_text='ORDERED classification root->leaf as provided by CoL (list of {rank,name}).'),
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='dataset_code',
            field=models.CharField(db_index=True, help_text='Actual dataset (e.g. COL25.12, 3LR, ...)', max_length=32),
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='external_id',
            field=models.CharField(db_index=True, help_text='External ID in the source', max_length=128),
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent taxon (internal FK) if already imported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.externaltaxon'),
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='parent_external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Parent external_id (to reconstruct tree)', max_length=128),
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='raw',
            field=models.JSONField(default=dict, help_text='Original payload (audit)'),
        ),
        migrations.AlterField(
            model_name='externaltaxon',
            name='system',
            field=models.CharField(db_index=True, default='col', help_text="External source (e.g. 'col')", max_length=32),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='accession',
            field=models.CharField(db_index=True, help_text='Assembly accession (e.g. GCF_000001405.40)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='annotation_provider',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Annotation provider (NCBI RefSeq, WormBase, etc.)', max_length=128),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='annotation_status',
            field=models.CharField(blank=True, default='', help_text='Annotation status (Full annotation, etc.)', max_length=64),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='assembly_method',
            field=models.CharField(blank=True, default='', help_text='Assembly method', max_length=255),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='busco_complete',
            field=models.FloatField(blank=True, help_text='BUSCO: % complete genes', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='busco_duplicated',
            field=models.FloatField(blank=True, help_text='BUSCO: % duplicated', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='busco_fragmented',
            field=models.FloatField(blank=True, help_text='BUSCO: % fragmented', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='busco_lineage',
            field=models.CharField(blank=True, default='', help_text='BUSCO lineage used (e.g. actinopterygii_odb10)', max_length=64),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='busco_missing',
            field=models.FloatField(blank=True, help_text='BUSCO: % missing', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='chromosome_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of chromosomes', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='col_match_notes',
            field=models.TextField(blank=True, default='', help_text='Notes about CoL matching'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='col_match_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('needs_review', 'Needs review'), ('no_match', 'No match in CoL')], db_index=True, default='unmatched', help_text='CoL linking status', max_length=32),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='common_name',
            field=models.CharField(blank=True, default='', help_text='Organism common name', max_length=255),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='contig_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of contigs', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='contig_n50_kb',
            field=models.FloatField(blank=True, help_text='Contig N50 in kilobases', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='directory_name',
            field=models.CharField(blank=True, default='', help_text='NCBI directory name', max_length=255),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='ecotype',
            field=models.CharField(blank=True, default='', help_text='Organism ecotype', max_length=128),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='external_taxon',
            field=models.ForeignKey(blank=True, help_text='Linked CoL taxon (via matching)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncbi_genomes', to='taxonomy.externaltaxon'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data fetch date'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='gc_percent',
            field=models.FloatField(blank=True, help_text='Genome GC percentage', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='genes',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of genes', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='genome_coverage',
            field=models.FloatField(blank=True, help_text='Genome coverage', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='has_proteome',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates whether it has a valid proteome (.faa)'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='is_best_for_taxon',
            field=models.BooleanField(db_index=True, default=False, help_text='Best assembly for this taxon'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='is_selected',
            field=models.BooleanField(db_index=True, default=False, help_text='Marked as selected for research'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='non_coding_genes',
            field=models.PositiveIntegerField(blank=True, help_text='Number of non-coding genes', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='protein_coding',
            field=models.PositiveIntegerField(blank=True, help_text='Number of protein-coding genes', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='proteome_quality',
            field=models.CharField(blank=True, default='', help_text='Proteome quality: good / poor / unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='pseudogenes',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pseudogenes', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='quality_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Computed quality score'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='raw',
            field=models.JSONField(default=dict, help_text='Original NCBI API payload'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='release_date',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Assembly release date', max_length=20),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='scaffold_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of scaffolds', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='scaffold_n50_kb',
            field=models.FloatField(blank=True, help_text='Scaffold N50 in kilobases', null=True),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='sequencing_tech',
            field=models.CharField(blank=True, default='', help_text='Sequencing technology', max_length=255),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='source_database',
            field=models.CharField(blank=True, db_index=True, default='', help_text='refseq or genbank', max_length=16),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='strain',
            field=models.CharField(blank=True, default='', help_text='Organism strain', max_length=128),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='taxon',
            field=models.ForeignKey(help_text='Associated NCBI taxon', on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='taxonomy.taxon'),
        ),
        migrations.AlterField(
            model_name='ncbigenome',
            name='total_sequence_length',
            field=models.BigIntegerField(blank=True, help_text='Total genome size in bp', null=True),
        ),
        migrations.AlterField(
            model_name='ncbisyncrun',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Celery task ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='ncbisyncrun',
            name='config',
            field=models.JSONField(default=dict, help_text='Configuration used for this synchronization'),
        ),
        migrations.AlterField(
            model_name='ncbisyncrun',
            name='log',
            field=models.JSONField(default=list, help_text='Detailed execution log'),
        ),
        migrations.AlterField(
            model_name='ncbisyncrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='ncbisyncrun',
            name='trigger',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('webhook', 'Webhook')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='taxonsyncrun',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Celery task ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonsyncrun',
            name='config',
            field=models.JSONField(default=dict, help_text='Synchronization configuration (limit, filters, etc.)'),
        ),
        migrations.AlterField(
            model_name='taxonsyncrun',
            name='log',
            field=models.JSONField(default=list, help_text='Detailed execution log'),
        ),
        migrations.AlterField(
            model_name='taxonsyncrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fetching_ncbi', 'Fetching NCBI'), ('matching_col', 'Matching COL'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24),
        ),
    ]
