# Generated by Django 5.2.9 on 2026-02-24 19:07

from django.db import migrations, models


def migrate_old_statuses(apps, schema_editor):
    """Convert old status values to new simplified scheme."""
    NCBIGenome = apps.get_model("taxonomy", "NCBIGenome")
    TaxonCrosswalk = apps.get_model("taxonomy", "TaxonCrosswalk")
    ResolutionItem = apps.get_model("taxonomy", "ResolutionItem")

    # NCBIGenome: needs_review, no_match -> unmatched
    NCBIGenome.objects.filter(
        col_match_status__in=["needs_review", "no_match"]
    ).update(col_match_status="unmatched")

    # TaxonCrosswalk: needs_review -> high, no_match -> high
    TaxonCrosswalk.objects.filter(
        decision__in=["needs_review", "no_match"]
    ).update(decision="high")

    # ResolutionItem: needs_review -> high, no_match -> high
    ResolutionItem.objects.filter(
        decision__in=["needs_review", "no_match"]
    ).update(decision="high")


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_add_sampling_configuration'),
    ]

    operations = [
        # First migrate data, then alter fields
        migrations.RunPython(migrate_old_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ncbigenome',
            name='col_match_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('manual', 'Manual')], db_index=True, default='unmatched', help_text='CoL linking status', max_length=32),
        ),
        migrations.AlterField(
            model_name='resolutionitem',
            name='decision',
            field=models.CharField(blank=True, choices=[('high', 'High confidence'), ('manual', 'Manual curation')], db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='taxoncrosswalk',
            name='decision',
            field=models.CharField(choices=[('high', 'High confidence'), ('manual', 'Manual curation')], db_index=True, max_length=32),
        ),
    ]
