# Generated by Django 5.2.9 on 2026-02-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0015_simplify_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncbigenome',
            name='col_match_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('not_in_col', 'Not in COL'), ('manual', 'Manual')], db_index=True, default='unmatched', help_text='CoL linking status', max_length=32),
        ),
    ]
