# Generated by Django 5.2.9 on 2026-02-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0016_add_not_in_col_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonsyncrun',
            name='ncbi_skipped',
            field=models.PositiveIntegerField(default=0, help_text='Genomes skipped because they already exist in the database'),
        ),
    ]
