# Generated by Django 5.2.9 on 2026-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0017_add_ncbi_skipped_to_taxonsyncrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncbigenome',
            name='col_match_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('not_in_col', 'Not in COL'), ('manual', 'Manual'), ('mismatch', 'Mismatch – genus audit failed')], db_index=True, default='unmatched', help_text='CoL linking status', max_length=32),
        ),
        migrations.AlterField(
            model_name='samplingconfiguration',
            name='strategy',
            field=models.CharField(choices=[('none', 'None (natural order)'), ('random', 'Random'), ('proportional', 'Proportional'), ('balanced', 'Equal Sample Size')], default='proportional', help_text='Sampling strategy', max_length=32),
        ),
    ]
