# Generated by Django 6.0 on 2026-03-14 03:18

from django.db import migrations, models


def convert_statuses(apps, schema_editor):
    """Convert unmatched and mismatch to not_in_col."""
    NCBIGenome = apps.get_model("taxonomy", "NCBIGenome")
    NCBIGenome.objects.filter(col_match_status="unmatched").update(col_match_status="not_in_col")
    NCBIGenome.objects.filter(col_match_status="mismatch").update(col_match_status="not_in_col")


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0018_add_mismatch_col_status'),
    ]

    operations = [
        # First convert data, then change field choices
        migrations.RunPython(convert_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ncbigenome',
            name='col_match_status',
            field=models.CharField(choices=[('matched', 'Matched'), ('not_in_col', 'Not in COL'), ('manual', 'Manual')], db_index=True, default='not_in_col', help_text='CoL linking status', max_length=32),
        ),
        migrations.AlterField(
            model_name='samplingconfiguration',
            name='strategy',
            field=models.CharField(choices=[('natural', 'Natural order'), ('quality_random', 'Quality Random'), ('stratified_proportional', 'Stratified Proportional'), ('balanced_hierarchical', 'Balanced Hierarchical')], default='stratified_proportional', help_text='Sampling strategy', max_length=32),
        ),
    ]
