# Generated by Django 6.0 on 2026-03-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0019_simplify_col_status_three_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncbigenome',
            name='col_match_status',
            field=models.CharField(choices=[('matched', 'Matched'), ('not_in_col', 'Not in COL'), ('manual', 'Manual')], db_index=True, default='not_in_col', help_text='CoL linking status', max_length=32),
        ),
    ]
