# Generated by Django 5.2.9 on 2026-03-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0021_alter_ncbigenome_col_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncbigenome',
            name='col_match_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('not_in_col', 'Not in COL'), ('manual', 'Manual'), ('mismatch', 'Mismatch – genus audit failed')], db_index=True, default='unmatched', help_text='CoL linking status', max_length=32),
        ),
    ]
