from apps.taxonomy.models import Taxon, NCBIGenome
t = Taxon.objects.count()
m = Taxon.objects.filter(genomes__col_match_status="matched").distinct().count()
n = Taxon.objects.filter(genomes__col_match_status="not_in_col").distinct().count()
x = Taxon.objects.filter(genomes__col_match_status="mismatch").distinct().count()
print(f"Total taxa: {t}")
print(f"COL matched taxa: {m}")
print(f"COL Coverage: {round(m/t*100)}%")
print(f"not_in_col: {n}")
print(f"mismatch (pending review): {x}")
print(f"Excluded: {n+x}")
